

development:
  adapter: postgresql
  encoding: unicode
  database: tableforchat1
  pool: 5
  username: shaitan
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: tableforchat2
  pool: 5
  username: shaitan
  password: 123456







